import React from 'react';
import Head from "next/head";
import Image from "next/image";
import Link from 'next/dist/client/link';

const Layout = ({children, title}) => {
    return (
        <div>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <header className='bg-black py-10 mb-5'>
                <Link href='/'>
                    <a>
                        <h1 className='text-6xl text-center text-amber-500'>{title}</h1>
                    </a>
                </Link>
            </header>

            <main className="container mx-auto">
                {children}
            </main>
        </div>
    );
};

export default Layout;
